import { describe, expect, it } from "vitest";
import { MOBILE_E2E_IDS } from "./e2eTestIds";

describe("MOBILE_E2E_IDS", () => {
  it("keeps the smoke-test selectors stable", () => {
    expect(MOBILE_E2E_IDS.appShell).toBe("mobile.app-shell");
    expect(MOBILE_E2E_IDS.appStartupLoading).toBe("mobile.app-startup-loading");
    expect(MOBILE_E2E_IDS.tasksScreen).toBe("mobile.tasks-screen");
    expect(MOBILE_E2E_IDS.tasksPairMacButton).toBe("mobile.tasks-pair-mac");
    expect(MOBILE_E2E_IDS.recentScreen).toBe("mobile.recent-screen");
    expect(MOBILE_E2E_IDS.searchScreen).toBe("mobile.search-screen");
    expect(MOBILE_E2E_IDS.searchInput).toBe("mobile.search-input");
    expect(MOBILE_E2E_IDS.searchKeyboardDismissTarget).toBe(
      "mobile.search-keyboard-dismiss-target"
    );
    expect(MOBILE_E2E_IDS.moreScreen).toBe("mobile.more-screen");
    expect(MOBILE_E2E_IDS.crashDiagnosticsCopy).toBe(
      "mobile.crash-diagnostics.copy"
    );
    expect(MOBILE_E2E_IDS.toolbarNavigation).toBe("mobile.toolbar.navigation");
    expect(MOBILE_E2E_IDS.toolbarSearch).toBe("mobile.toolbar.search");
    expect(MOBILE_E2E_IDS.taskDetailScreen).toBe("mobile.task-detail-screen");
    expect(MOBILE_E2E_IDS.taskDetailTitle).toBe("mobile.task-detail-title");
    expect(MOBILE_E2E_IDS.taskTitleButton).toBe("mobile.task-title-button");
    expect(MOBILE_E2E_IDS.taskExpandedPrompt).toBe(
      "mobile.task-expanded-prompt"
    );
    expect(MOBILE_E2E_IDS.taskTitleDismissLayer).toBe(
      "mobile.task-title-dismiss-layer"
    );
    expect(MOBILE_E2E_IDS.taskBackButton).toBe("mobile.task-back-button");
    expect(MOBILE_E2E_IDS.taskTopChrome).toBe("mobile.task-top-chrome");
    expect(MOBILE_E2E_IDS.taskDiffTitle).toBe("mobile.task-diff.title");
    expect(MOBILE_E2E_IDS.taskDiffBase).toBe("mobile.task-diff.base");
    expect(MOBILE_E2E_IDS.taskDiffClose).toBe("mobile.task-diff.close");
    expect(MOBILE_E2E_IDS.taskDiffError).toBe("mobile.task-diff.error");
    expect(MOBILE_E2E_IDS.taskDiffErrorMessage).toBe(
      "mobile.task-diff.error-message"
    );
    expect(MOBILE_E2E_IDS.taskDiffInspection).toBe(
      "mobile.task-diff.inspection"
    );
    expect(MOBILE_E2E_IDS.visualCompanionButton).toBe(
      "mobile.visual-companion.button"
    );
    expect(MOBILE_E2E_IDS.visualCompanionUnread).toBe(
      "mobile.visual-companion.unread"
    );
    expect(MOBILE_E2E_IDS.visualCompanionModal).toBe(
      "mobile.visual-companion.modal"
    );
    expect(MOBILE_E2E_IDS.visualCompanionClose).toBe(
      "mobile.visual-companion.close"
    );
    expect(MOBILE_E2E_IDS.visualCompanionStatus).toBe(
      "mobile.visual-companion.status"
    );
    expect(MOBILE_E2E_IDS.visualCompanionWebView).toBe(
      "mobile.visual-companion.webview"
    );
    expect(MOBILE_E2E_IDS.accountButton).toBe("mobile.account-button");
    expect(MOBILE_E2E_IDS.accountSheet).toBe("mobile.account-sheet");
    expect(MOBILE_E2E_IDS.accountCloseButton).toBe("mobile.account-close");
    expect(MOBILE_E2E_IDS.accountMachinesButton).toBe("mobile.account-machines");
    expect(MOBILE_E2E_IDS.accountRelayInput).toBe("mobile.account-relay-input");
    expect(MOBILE_E2E_IDS.accountRelaySaveButton).toBe("mobile.account-relay-save");
    expect(MOBILE_E2E_IDS.accountRelayResetButton).toBe("mobile.account-relay-reset");
    expect(MOBILE_E2E_IDS.machinesScreen).toBe("mobile.machines-screen");
    expect(MOBILE_E2E_IDS.machinesBackButton).toBe("mobile.machines-back");
    expect(MOBILE_E2E_IDS.machinesAddButton).toBe("mobile.machines-add");
    expect(MOBILE_E2E_IDS.machinePairingSheet).toBe("mobile.machine-pairing.sheet");
    expect(MOBILE_E2E_IDS.machinePairingCodeInput).toBe("mobile.machine-pairing.code");
    expect(MOBILE_E2E_IDS.machinePairingSubmitButton).toBe("mobile.machine-pairing.submit");
    expect(MOBILE_E2E_IDS.machinePairingProgress).toBe(
      "mobile.machine-pairing.progress"
    );
    expect(MOBILE_E2E_IDS.machinePairingError).toBe("mobile.machine-pairing.error");
    expect(MOBILE_E2E_IDS.machinePairingCloseButton).toBe("mobile.machine-pairing.close");
    expect(MOBILE_E2E_IDS.machinePairingCamera).toBe("mobile.machine-pairing.camera");
    expect(MOBILE_E2E_IDS.machinePairingScanModeButton).toBe(
      "mobile.machine-pairing.mode.scan"
    );
    expect(MOBILE_E2E_IDS.machinePairingOpenSettingsButton).toBe(
      "mobile.machine-pairing.open-settings"
    );
    expect(MOBILE_E2E_IDS.developerForceCloudToggle).toBe(
      "mobile.developer.force-cloud"
    );
    expect(MOBILE_E2E_IDS.machineRow("desktop-1")).toBe("mobile.machine.desktop-1");
    expect(MOBILE_E2E_IDS.machineName("desktop-1")).toBe(
      "mobile.machine.desktop-1.name"
    );
    expect(MOBILE_E2E_IDS.machineOrigin("desktop-1", "manual")).toBe(
      "mobile.machine.desktop-1.origin.manual"
    );
    expect(MOBILE_E2E_IDS.machineRemoveButton("desktop-1")).toBe(
      "mobile.machine.desktop-1.remove"
    );
    expect(MOBILE_E2E_IDS.accountEmailInput).toBe("mobile.account-email");
    expect(MOBILE_E2E_IDS.accountPasswordInput).toBe("mobile.account-password");
    expect(MOBILE_E2E_IDS.accountPasswordToggle).toBe(
      "mobile.account-toggle-password"
    );
    expect(MOBILE_E2E_IDS.accountSignInButton).toBe("mobile.account-sign-in");
    expect(MOBILE_E2E_IDS.accountSignOutButton).toBe("mobile.account-sign-out");
    expect(MOBILE_E2E_IDS.taskCreationRecoverButton).toBe(
      "mobile.task-creation.recover"
    );
    expect(MOBILE_E2E_IDS.taskBlockedPlaceholder).toBe(
      "mobile.task-blocked-placeholder"
    );
    expect(MOBILE_E2E_IDS.createTaskCancelButton).toBe(
      "mobile.create-task.cancel"
    );
    expect(MOBILE_E2E_IDS.createTaskSheetScroll).toBe(
      "mobile.create-task.sheet-scroll"
    );
    expect(MOBILE_E2E_IDS.toolbarUtilityAction("create")).toBe(
      "mobile.toolbar.utility.create"
    );
    expect(MOBILE_E2E_IDS.moreCommand("compose")).toBe(
      "mobile.more.command.compose"
    );
    expect(MOBILE_E2E_IDS.moreRepo("repo-1")).toBe(
      "mobile.more.repo.repo-1"
    );
    expect(MOBILE_E2E_IDS.moreRetryButton).toBe(
      "mobile.more-retry-button"
    );
    expect(MOBILE_E2E_IDS.moreCommandGroup("configure")).toBe(
      "mobile.more.command-group.configure"
    );
    expect(MOBILE_E2E_IDS.taskListItem("task-1")).toBe("mobile.task-row.task-1");
    expect(MOBILE_E2E_IDS.taskListSubtaskRow("task-1")).toBe(
      "mobile.task-row.task-1.subtask"
    );
  });
});
