export const MOBILE_E2E_IDS = {
  appShell: "mobile.app-shell",
  moreScreen: "mobile.more-screen",
  tasksScreen: "mobile.tasks-screen",
  recentScreen: "mobile.recent-screen",
  searchScreen: "mobile.search-screen",
  toolbarNavigation: "mobile.toolbar.navigation",
  toolbarSearch: "mobile.toolbar.search",
  taskDetailScreen: "mobile.task-detail-screen",
  taskDetailTitle: "mobile.task-detail-title",
  taskTitleButton: "mobile.task-title-button",
  taskExpandedPrompt: "mobile.task-expanded-prompt",
  taskExpandedTaskId: "mobile.task-expanded-task-id",
  taskTitleDismissLayer: "mobile.task-title-dismiss-layer",
  taskSnapshotMarker: "mobile.task-snapshot-marker",
  taskBackButton: "mobile.task-back-button",
  taskMoreButton: "mobile.task-more-button",
  taskComposerChrome: "mobile.task-composer-chrome",
  taskInput: "mobile.task-input",
  taskSendButton: "mobile.task-send-button",
  taskStopButton: "mobile.task-stop-button",
  agentMessageView: "mobile.agent-message-view",
  agentMessageReady: "mobile.agent-message-ready",
  terminalOverlay: "mobile.terminal-overlay",
  taskCreationRecoverButton: "mobile.task-creation.recover",
  terminalInspection: "mobile.terminal-inspection",
  taskFilePreviewPath: "mobile.task-file-preview.path",
  taskFilePreviewMode: "mobile.task-file-preview.mode",
  taskFilePreviewClose: "mobile.task-file-preview.close",
  taskFilePreviewError: "mobile.task-file-preview.error",
  taskFilePreviewErrorMessage: "mobile.task-file-preview.error-message",
  taskFilePreviewInspection: "mobile.task-file-preview.inspection",
  accountButton: "mobile.account-button",
  accountSheet: "mobile.account-sheet",
  accountCloseButton: "mobile.account-close",
  accountConnectionStatus: "mobile.account-connection-status",
  accountConnectionTitle: "mobile.account-connection-title",
  accountConnectLocalButton: "mobile.account-connect-local",
  accountForceCloudToggle: "mobile.account-force-cloud",
  accountEmailInput: "mobile.account-email",
  accountPasswordInput: "mobile.account-password",
  accountPasswordToggle: "mobile.account-toggle-password",
  accountSignInButton: "mobile.account-sign-in",
  accountSignOutButton: "mobile.account-sign-out",
  createTaskPromptInput: "mobile.create-task.prompt",
  createTaskSubmitButton: "mobile.create-task.submit",
  createTaskError: "mobile.create-task.error",
  createTaskOptionsToggle: "mobile.create-task.options-toggle",
  createTaskMachineOption(desktopId: string): string {
    return `mobile.create-task.machine.${desktopId}`;
  },
  createTaskAgentOption(provider: string): string {
    return `mobile.create-task.agent.${provider}`;
  },
  updateReadyBanner: "mobile.update-ready",
  updateReadyDismissButton: "mobile.update-ready.dismiss",
  updateReadyRestartButton: "mobile.update-ready.restart",
  toolbarTab(tabName: string): string {
    return `mobile.toolbar.tab.${tabName}`;
  },
  taskListItem(taskId: string): string {
    return `mobile.task-row.${taskId}`;
  }
} as const;
