packages:
  - "apps/*"
  - "packages/*"
  - "services/*"
  - "tests/*"
  - "tools/*"
enableGlobalVirtualStore: true
hoist: false
confirmModulesPurge: false
allowBuilds:
  '@firebase/util': false
  appium: false
  edgedriver: false
  esbuild: false
  geckodriver: false
  protobufjs: false
  re2: false
  sharp: false
onlyBuiltDependencies: []
packageExtensions:
  "@apphosting/build@0.1.7":
    dependencies:
      yaml: 2.8.3
  "@expo/cli@0.24.24":
    dependencies:
      "@react-native/js-polyfills": 0.79.2
      expo: 53.0.27
      expo-constants: 17.1.8
      metro: 0.82.5
      metro-config: 0.82.5
      metro-core: 0.82.5
      metro-resolver: 0.82.5
      metro-runtime: 0.82.5
  "@expo/metro-config@0.20.18":
    dependencies:
      "@babel/code-frame": 7.29.0
      "@babel/template": 7.28.6
      "@babel/traverse": 7.29.0
      "@react-native/js-polyfills": 0.79.2
      babel-preset-expo: 13.2.5
      expo: 53.0.27
      hermes-parser: 0.25.1
      metro: 0.82.5
      metro-cache: 0.82.5
      metro-cache-key: 0.82.5
      metro-config: 0.82.5
      metro-minify-terser: 0.82.5
      metro-source-map: 0.82.5
      metro-transform-plugins: 0.82.5
      metro-transform-worker: 0.82.5
