import { createHash, timingSafeEqual } from "node:crypto";
import { getFirebaseServices } from "./firebase.js";

/**
 * Upper bound on desktops docs fetched per credential check. A desktopId is a
 * UUID generated by the desktop app, so more than one match only happens if
 * another user writes the same desktopId into their own subcollection; the
 * secret-hash comparison below still selects the correct owner.
 */
const DESKTOP_LOOKUP_LIMIT = 10;

/**
 * Verify a Firebase Auth ID token (sent by the phone client).
 * Returns the userId or null if verification fails.
 */
export async function verifyPhoneToken(
  idToken: string
): Promise<string | null> {
  try {
    const { auth } = getFirebaseServices();
    const decoded = await auth.verifyIdToken(idToken);
    return decoded.uid;
  } catch (err) {
    console.error("[auth] Failed to verify phone token:", err);
    return null;
  }
}

/**
 * Verify a device token (sent by kanna-server).
 * Looks up the device token in Firestore: devices/{deviceToken}.userId
 * Returns the userId or null if not found.
 */
export async function verifyDeviceToken(
  deviceToken: string
): Promise<string | null> {
  try {
    const { db } = getFirebaseServices();
    const doc = await db.collection("devices").doc(deviceToken).get();
    if (!doc.exists) {
      console.warn("[auth] Device token not found:", deviceToken);
      return null;
    }
    const data = doc.data();
    return (data?.userId as string) ?? null;
  } catch (err) {
    console.error("[auth] Failed to verify device token:", err);
    return null;
  }
}

export interface DesktopPrincipal {
  userId: string;
  desktopId: string;
}

export type ServerAuthProof =
  | { kind: "desktop"; desktopId: string; desktopSecret: string }
  | { kind: "device"; desktopId: string; deviceToken: string };

export async function revalidateServerAuth(
  proof: ServerAuthProof,
  expectedUserId: string,
  expectedDesktopId: string,
): Promise<boolean> {
  if (proof.desktopId !== expectedDesktopId) return false;
  if (proof.kind === "desktop") {
    const principal = await verifyDesktopCredentials(proof.desktopId, proof.desktopSecret);
    return principal?.userId === expectedUserId && principal.desktopId === expectedDesktopId;
  }
  // A legacy device token proves account membership only. It cannot prove that
  // the caller owns the supplied desktop ID, so it is never valid for
  // desktop-scoped snapshot or transfer-identity publication.
  return false;
}

export function hashDesktopSecret(desktopSecret: string): string {
  return createHash("sha256").update(desktopSecret, "utf8").digest("hex");
}

export function desktopSecretMatchesHash(
  desktopSecret: string,
  desktopSecretHash: unknown
): boolean {
  if (typeof desktopSecretHash !== "string" || desktopSecretHash.length === 0) {
    return false;
  }

  const actual = Buffer.from(hashDesktopSecret(desktopSecret), "hex");
  const expected = Buffer.from(desktopSecretHash, "hex");
  return actual.length === expected.length && timingSafeEqual(actual, expected);
}

export async function verifyDesktopCredentials(
  desktopId: string,
  desktopSecret: string
): Promise<DesktopPrincipal | null> {
  try {
    const { db } = getFirebaseServices();
    const credentialDoc = await db
      .collection("desktopCredentials")
      .doc(desktopDocumentId(desktopId))
      .get();
    if (credentialDoc.exists) {
      const data = credentialDoc.data();
      if (data?.desktopId !== desktopId
        || data?.revokedAt
        || typeof data?.uid !== "string"
        || !desktopSecretMatchesHash(desktopSecret, data?.desktopSecretHash)) {
        console.warn("[auth] Canonical desktop credentials rejected:", desktopId);
        return null;
      }
      return { userId: data.uid, desktopId };
    }

    const snapshot = await db
      .collectionGroup("desktops")
      .where("desktopId", "==", desktopId)
      .limit(DESKTOP_LOOKUP_LIMIT)
      .get();

    if (snapshot.empty) {
      console.warn("[auth] Desktop not found:", desktopId);
      return null;
    }

    const matchingPrincipals: DesktopPrincipal[] = [];
    for (const doc of snapshot.docs) {
      const data = doc.data();
      if (data.revokedAt) {
        continue;
      }

      if (!desktopSecretMatchesHash(desktopSecret, data.desktopSecretHash)) {
        continue;
      }

      const userDoc = doc.ref.parent.parent;
      if (!userDoc) {
        console.warn("[auth] Desktop missing parent user:", desktopId);
        continue;
      }

      matchingPrincipals.push({
        userId: userDoc.id,
        desktopId,
      });
    }

    const userIds = new Set(matchingPrincipals.map((principal) => principal.userId));
    if (userIds.size === 1) return matchingPrincipals[0];
    if (userIds.size > 1) {
      console.warn("[auth] Ambiguous legacy desktop ownership:", desktopId);
      return null;
    }

    console.warn("[auth] Desktop credentials rejected:", desktopId);
    return null;
  } catch (err) {
    console.error("[auth] Failed to verify desktop credentials:", err);
    return null;
  }
}

function desktopDocumentId(desktopId: string): string {
  if (desktopId === "." || desktopId === "..") {
    return `desktop-${Buffer.from(desktopId).toString("hex")}`;
  }
  return desktopId.replaceAll("/", "_");
}

/**
 * Register a device token for a user.
 * Called from POST /register after phone auth verification.
 */
export async function registerDevice(
  userId: string,
  deviceToken: string
): Promise<void> {
  try {
    const { db } = getFirebaseServices();
    await db.collection("devices").doc(deviceToken).set({
      userId,
      createdAt: new Date().toISOString(),
    });
    console.log(
      `[auth] Registered device ${deviceToken} for user ${userId}`
    );
  } catch (err) {
    console.error("[auth] Failed to register device:", err);
    throw err;
  }
}
