import { createHash, timingSafeEqual } from "node:crypto";
import { getFirebaseServices } from "./firebase.js";

/**
 * Upper bound on desktops docs fetched per credential check. A desktopId is a
 * UUID generated by the desktop app, so more than one match only happens if
 * another user writes the same desktopId into their own subcollection; the
 * secret-hash comparison below still selects the correct owner.
 */
const DESKTOP_LOOKUP_LIMIT = 10;
const ACCOUNT_DELETIONS_COLLECTION = "accountDeletions";

export class AccountDeletionInProgressError extends Error {
  constructor() {
    super("account deletion is in progress");
    this.name = "AccountDeletionInProgressError";
  }
}

/**
 * How long a successful `desktopCredentials` validation stays usable for
 * per-message revalidation.
 *
 * The tradeoff: `revalidateServerAuth` runs on every published message and
 * every invoke, so an uncached read costs ~1-2M Firestore reads/month per
 * active desktop for a document that only changes at sign-in and sign-out.
 * Against that, the TTL is the window in which a credential revoked out from
 * under us is still honoured on an *already open* socket — the relay handles
 * no `desktopCredentials` write of its own (see
 * `invalidateDesktopCredentialCache`), so this bound is the real revocation
 * latency, not a backstop behind a write hook. 60s keeps that window shorter
 * than a desktop's 5s reconnect loop takes to matter while removing
 * essentially all of the read cost.
 */
export const DEFAULT_DESKTOP_CREDENTIAL_CACHE_TTL_MS = 60_000;

/**
 * Override for the TTL above. `0` disables the cache entirely, restoring a
 * Firestore read per revalidation — the escape hatch if a deployment ever
 * needs revocation to be immediate, and what the integration suite turns down
 * so it can observe the bound instead of waiting a minute for it.
 */
export function resolveDesktopCredentialCacheTtlMs(
  env: NodeJS.ProcessEnv = process.env,
): number {
  const raw = env.KANNA_RELAY_DESKTOP_CREDENTIAL_CACHE_TTL_MS?.trim();
  if (!raw) return DEFAULT_DESKTOP_CREDENTIAL_CACHE_TTL_MS;
  const parsed = Number(raw);
  if (!Number.isFinite(parsed) || parsed < 0) {
    console.warn(
      `[auth] Ignoring invalid KANNA_RELAY_DESKTOP_CREDENTIAL_CACHE_TTL_MS=${raw}`,
    );
    return DEFAULT_DESKTOP_CREDENTIAL_CACHE_TTL_MS;
  }
  return Math.floor(parsed);
}

const desktopCredentialCacheTtlMs = resolveDesktopCredentialCacheTtlMs();

/**
 * Hard cap on cached desktops, so a relay that sees many desktops over its
 * lifetime cannot grow this map without bound on a 1 GB VM. Entries are tiny
 * (two strings and two numbers); the cap exists for the shape, not the size.
 */
export const DESKTOP_CREDENTIAL_CACHE_MAX_ENTRIES = 10_000;

interface CachedDesktopCredential {
  /** Hash of the secret Firestore accepted, re-checked on every hit. */
  desktopSecretHash: string;
  principal: DesktopPrincipal;
  expiresAtMs: number;
}

/**
 * Keyed by desktopId so invalidation is a single delete. The validated
 * secret's hash rides along in the entry rather than in the key: a hit must
 * prove the caller presented the same secret Firestore accepted, and a
 * different secret for the same desktop is a miss that re-reads Firestore.
 */
const desktopCredentialCache = new Map<string, CachedDesktopCredential>();

function cachedDesktopPrincipal(
  desktopId: string,
  desktopSecret: string,
  nowMs: number,
): DesktopPrincipal | null {
  const entry = desktopCredentialCache.get(desktopId);
  if (!entry) return null;
  if (entry.expiresAtMs <= nowMs) {
    desktopCredentialCache.delete(desktopId);
    return null;
  }
  if (!desktopSecretMatchesHash(desktopSecret, entry.desktopSecretHash)) {
    return null;
  }
  return entry.principal;
}

/**
 * Record a validation Firestore just accepted. Only ever called on success:
 * rejections and Firestore errors are deliberately not cached, so a transient
 * outage degrades to today's behaviour instead of pinning a wrong answer.
 */
function cacheDesktopCredential(
  desktopId: string,
  desktopSecret: string,
  principal: DesktopPrincipal,
  nowMs: number,
): void {
  desktopCredentialCache.delete(desktopId);
  if (desktopCredentialCacheTtlMs <= 0) return;
  if (desktopCredentialCache.size >= DESKTOP_CREDENTIAL_CACHE_MAX_ENTRIES) {
    evictForCapacity(nowMs);
  }
  desktopCredentialCache.set(desktopId, {
    desktopSecretHash: hashDesktopSecret(desktopSecret),
    principal,
    expiresAtMs: nowMs + desktopCredentialCacheTtlMs,
  });
}

/** Drop expired entries first; fall back to oldest-inserted. */
function evictForCapacity(nowMs: number): void {
  for (const [desktopId, entry] of desktopCredentialCache) {
    if (entry.expiresAtMs <= nowMs) desktopCredentialCache.delete(desktopId);
  }
  while (desktopCredentialCache.size >= DESKTOP_CREDENTIAL_CACHE_MAX_ENTRIES) {
    const oldest = desktopCredentialCache.keys().next();
    if (oldest.done) return;
    desktopCredentialCache.delete(oldest.value);
  }
}

/**
 * Drop a desktop's cached validation (or the whole cache when no id is given).
 *
 * The relay itself writes no `desktopCredentials` document — sign-in and
 * sign-out are written directly by the desktop app
 * (`apps/desktop/src/services/desktopCloudAssociation.ts`), and this service's
 * own mutators (`registerDevice`, `registerPushDevice`,
 * `unregisterPushDevice`) touch unrelated collections. So this is exported for
 * a future relay-side mutator, and wired today to the one place the relay
 * learns first-hand that a credential went bad: an authoritative rejection in
 * `verifyDesktopCredentials`, which is how a desktop reconnecting after
 * sign-out flushes the entry still serving its previous socket.
 */
export function invalidateDesktopCredentialCache(desktopId?: string): void {
  if (desktopId === undefined) {
    desktopCredentialCache.clear();
    return;
  }
  desktopCredentialCache.delete(desktopId);
}

export interface PhonePrincipal {
  userId: string;
  /**
   * The token's `email_verified` claim. Entitlement enforcement refuses an
   * unverified phone token outright (`docs/specs/accounts-and-billing.md`,
   * Decision 1: an unverified account cannot activate an entitlement).
   */
  emailVerified: boolean;
}

/**
 * Verify a Firebase Auth ID token (sent by the phone client).
 * Returns the principal or null if verification fails.
 */
export async function verifyPhoneIdentity(
  idToken: string
): Promise<PhonePrincipal | null> {
  try {
    const { auth } = getFirebaseServices();
    const decoded = await auth.verifyIdToken(idToken);
    return { userId: decoded.uid, emailVerified: decoded.email_verified === true };
  } catch (err) {
    console.error("[auth] Failed to verify phone token:", err);
    return null;
  }
}

/** The uid alone, for the routes that only need to know who is calling. */
export async function verifyPhoneToken(
  idToken: string
): Promise<string | null> {
  return (await verifyPhoneIdentity(idToken))?.userId ?? null;
}

/**
 * Verify a device token (sent by kanna-server).
 * Looks up the device token in Firestore: devices/{deviceToken}.userId
 * Returns the userId or null if not found.
 */
export async function verifyDeviceToken(
  deviceToken: string
): Promise<string | null> {
  try {
    const { db } = getFirebaseServices();
    const doc = await db.collection("devices").doc(deviceToken).get();
    if (!doc.exists) {
      console.warn("[auth] Device token not found:", deviceToken);
      return null;
    }
    const data = doc.data();
    return (data?.userId as string) ?? null;
  } catch (err) {
    console.error("[auth] Failed to verify device token:", err);
    return null;
  }
}

export interface DesktopPrincipal {
  userId: string;
  desktopId: string;
}

export type ServerAuthProof =
  | { kind: "desktop"; desktopId: string; desktopSecret: string }
  | { kind: "device"; desktopId: string; deviceToken: string };

export async function revalidateServerAuth(
  proof: ServerAuthProof,
  expectedUserId: string,
  expectedDesktopId: string,
): Promise<boolean> {
  if (proof.desktopId !== expectedDesktopId) return false;
  if (proof.kind === "desktop") {
    // The hot path: every published message and every invoke lands here. A
    // cache hit is a validation Firestore already accepted for this exact
    // secret, at most one TTL window ago. Establishing a
    // connection deliberately does not read the cache — see
    // verifyDesktopCredentials — so a revoked desktop can never open a fresh
    // socket, only finish out the TTL on one it already holds.
    const principal = cachedDesktopPrincipal(
      proof.desktopId,
      proof.desktopSecret,
      Date.now(),
    ) ?? await verifyDesktopCredentials(proof.desktopId, proof.desktopSecret);
    return principal?.userId === expectedUserId && principal.desktopId === expectedDesktopId;
  }
  // A legacy device token proves account membership only. It cannot prove that
  // the caller owns the supplied desktop ID, so it is never valid for
  // desktop-scoped snapshot or transfer-identity publication.
  return false;
}

export function hashDesktopSecret(desktopSecret: string): string {
  return createHash("sha256").update(desktopSecret, "utf8").digest("hex");
}

export function desktopSecretMatchesHash(
  desktopSecret: string,
  desktopSecretHash: unknown
): boolean {
  if (typeof desktopSecretHash !== "string" || desktopSecretHash.length === 0) {
    return false;
  }

  const actual = Buffer.from(hashDesktopSecret(desktopSecret), "hex");
  const expected = Buffer.from(desktopSecretHash, "hex");
  return actual.length === expected.length && timingSafeEqual(actual, expected);
}

/**
 * Authoritative desktop-credential check: always reads Firestore, never the
 * cache. This is what a *new* connection authenticates against, so revoking a
 * desktop locks it out of the relay immediately.
 *
 * It writes through to the cache on success — which is what makes the
 * revalidation immediately following a handshake a hit rather than a second
 * read — and purges on an authoritative rejection.
 */
export async function verifyDesktopCredentials(
  desktopId: string,
  desktopSecret: string
): Promise<DesktopPrincipal | null> {
  let principal: DesktopPrincipal | null;
  try {
    principal = await readDesktopCredentials(desktopId, desktopSecret);
  } catch (err) {
    // Firestore is unavailable, which is not evidence about the credential.
    // Leave any cached validation alone: flushing it here would turn an
    // outage into a disconnect for every live desktop.
    console.error("[auth] Failed to verify desktop credentials:", err);
    return null;
  }
  if (!principal) {
    invalidateDesktopCredentialCache(desktopId);
    return null;
  }
  cacheDesktopCredential(desktopId, desktopSecret, principal, Date.now());
  return principal;
}

/**
 * The Firestore read itself. Returns null only for an *authoritative*
 * rejection; an unavailable Firestore throws, so the caller can tell the two
 * apart.
 */
async function readDesktopCredentials(
  desktopId: string,
  desktopSecret: string
): Promise<DesktopPrincipal | null> {
  const { db } = getFirebaseServices();
  const credentialDoc = await db
    .collection("desktopCredentials")
    .doc(desktopDocumentId(desktopId))
    .get();
  if (credentialDoc.exists) {
    const data = credentialDoc.data();
    if (data?.desktopId !== desktopId
      || data?.revokedAt
      || typeof data?.uid !== "string"
      || !desktopSecretMatchesHash(desktopSecret, data?.desktopSecretHash)) {
      console.warn("[auth] Canonical desktop credentials rejected:", desktopId);
      return null;
    }
    return { userId: data.uid, desktopId };
  }

  const snapshot = await db
    .collectionGroup("desktops")
    .where("desktopId", "==", desktopId)
    .limit(DESKTOP_LOOKUP_LIMIT)
    .get();

  if (snapshot.empty) {
    console.warn("[auth] Desktop not found:", desktopId);
    return null;
  }

  const matchingPrincipals: DesktopPrincipal[] = [];
  for (const doc of snapshot.docs) {
    const data = doc.data();
    if (data.revokedAt) {
      continue;
    }

    if (!desktopSecretMatchesHash(desktopSecret, data.desktopSecretHash)) {
      continue;
    }

    const userDoc = doc.ref.parent.parent;
    if (!userDoc) {
      console.warn("[auth] Desktop missing parent user:", desktopId);
      continue;
    }

    matchingPrincipals.push({
      userId: userDoc.id,
      desktopId,
    });
  }

  const userIds = new Set(matchingPrincipals.map((principal) => principal.userId));
  if (userIds.size === 1) return matchingPrincipals[0];
  if (userIds.size > 1) {
    console.warn("[auth] Ambiguous legacy desktop ownership:", desktopId);
    return null;
  }

  console.warn("[auth] Desktop credentials rejected:", desktopId);
  return null;
}

function desktopDocumentId(desktopId: string): string {
  if (desktopId === "." || desktopId === "..") {
    return `desktop-${Buffer.from(desktopId).toString("hex")}`;
  }
  return desktopId.replaceAll("/", "_");
}

/**
 * Register a device token for a user.
 * Called from POST /register after phone auth verification.
 */
export async function registerDevice(
  userId: string,
  deviceToken: string
): Promise<void> {
  try {
    const { db } = getFirebaseServices();
    await db.runTransaction(async (transaction) => {
      const deletion = await transaction.get(
        db.collection(ACCOUNT_DELETIONS_COLLECTION).doc(userId),
      );
      if (deletion.exists) throw new AccountDeletionInProgressError();
      transaction.set(db.collection("devices").doc(deviceToken), {
        userId,
        createdAt: new Date().toISOString(),
      });
    });
    console.log(
      `[auth] Registered device ${deviceToken} for user ${userId}`
    );
  } catch (err) {
    if (err instanceof AccountDeletionInProgressError) throw err;
    console.error("[auth] Failed to register device:", err);
    throw err;
  }
}

export async function registerPushDevice(
  userId: string,
  deviceId: string,
  deviceToken: string
): Promise<void> {
  try {
    const { db } = getFirebaseServices();
    await db.runTransaction(async (transaction) => {
      const deletion = await transaction.get(
        db.collection(ACCOUNT_DELETIONS_COLLECTION).doc(userId),
      );
      if (deletion.exists) throw new AccountDeletionInProgressError();
      transaction.set(
        db
          .collection("users")
          .doc(userId)
          .collection("pushDevices")
          .doc(hashPushDeviceId(deviceId)),
        {
          deviceId,
          token: deviceToken,
          updatedAt: new Date().toISOString(),
        },
        { merge: true },
      );
    });
    console.log(
      `[auth] Registered mobile push device ${deviceId} for user ${userId}`
    );
  } catch (err) {
    if (err instanceof AccountDeletionInProgressError) throw err;
    console.error("[auth] Failed to register mobile push device:", err);
    throw err;
  }
}

export async function unregisterPushDevice(
  userId: string,
  deviceId: string
): Promise<void> {
  try {
    const { db } = getFirebaseServices();
    await db
      .collection("users")
      .doc(userId)
      .collection("pushDevices")
      .doc(hashPushDeviceId(deviceId))
      .delete();
  } catch (err) {
    console.error("[auth] Failed to unregister mobile push device:", err);
    throw err;
  }
}

function hashPushDeviceId(deviceId: string): string {
  return createHash("sha256").update(deviceId, "utf8").digest("hex");
}
