import { describe, expect, it } from "vitest";
import {
  buildMobileDeviceRunCommand,
  checkPhysicalDeviceRunPreflight,
  patchPbxprojNativeIdentity,
  resolveMobileNativeIdentity,
  writeMobileNativeIdentityConfig,
  parseXcdeviceList,
  selectPhysicalDevice
} from "../src/runtime/mobile-device";
import type { CommandRunner } from "../src/runtime/process";
import { mkdir, mkdtemp, readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

function device(name: string, udid: string) {
  return { name, udid, platformVersion: "17.5" };
}

describe("physical-device mobile runtime", () => {
  it("selects the requested attached iPhone by UDID or name", () => {
    const devices = [
      device("Jeremy's iPhone", "udid-1"),
      device("Jerome's iPhone 15", "udid-2")
    ];

    expect(selectPhysicalDevice(devices, { requestedUdid: "udid-2" })).toMatchObject({
      name: "Jerome's iPhone 15",
      udid: "udid-2"
    });
    expect(selectPhysicalDevice(devices, { requestedName: "Jeremy's iPhone" })).toMatchObject({
      name: "Jeremy's iPhone",
      udid: "udid-1"
    });
  });

  it("parses attached physical iPhones from xcdevice JSON", () => {
    expect(
      parseXcdeviceList(`[
        {
          "available": true,
          "identifier": "00008130-001015CA1091401C",
          "name": "Jerome's iPhone 15",
          "operatingSystemVersion": "17.5 (21F79)",
          "platform": "com.apple.platform.iphoneos",
          "simulator": false
        },
        {
          "available": true,
          "identifier": "390F2D5A-D8FE-40BC-9D42-DBA11DD35BF2",
          "name": "iPhone 15",
          "platform": "com.apple.platform.iphonesimulator",
          "simulator": true
        }
      ]`)
    ).toEqual([
      {
        name: "Jerome's iPhone 15",
        udid: "00008130-001015CA1091401C",
        platformVersion: "17.5"
      }
    ]);
  });

  it("resolves the native bundle id and display name from KANNA_APP_ENV", () => {
    expect(resolveMobileNativeIdentity({ KANNA_APP_ENV: "dev" })).toEqual({
      appEnv: "dev",
      bundleId: "build.kanna.app.dev",
      displayName: "Kanna Dev"
    });
    expect(resolveMobileNativeIdentity({ KANNA_APP_ENV: "staging" })).toEqual({
      appEnv: "staging",
      bundleId: "build.kanna.app.staging",
      displayName: "Kanna Staging"
    });
    expect(resolveMobileNativeIdentity({ KANNA_APP_ENV: "production" })).toEqual({
      appEnv: "prod",
      bundleId: "build.kanna.app",
      displayName: "Kanna"
    });
  });

  it("writes an xcconfig consumed by committed iOS builds", async () => {
    const repoRoot = await mkdtemp(join(tmpdir(), "kanna-native-identity-"));
    await mkdir(join(repoRoot, "apps/mobile/ios"), { recursive: true });

    const result = await writeMobileNativeIdentityConfig(repoRoot, {
      KANNA_APP_ENV: "staging"
    });

    expect(result).toEqual({
      appEnv: "staging",
      bundleId: "build.kanna.app.staging",
      displayName: "Kanna Staging",
      path: join(repoRoot, "apps/mobile/ios/KannaNativeIdentity.xcconfig")
    });
    await expect(readFile(result.path, "utf8")).resolves.toBe(
      [
        "// Generated by kd. Do not edit.",
        "KANNA_BUNDLE_ID = build.kanna.app.staging",
        "KANNA_DISPLAY_NAME = Kanna Staging",
        ""
      ].join("\n")
    );
  });

  it("does not create an empty iOS project when native sources are absent", async () => {
    const repoRoot = await mkdtemp(join(tmpdir(), "kanna-native-identity-"));

    const result = await writeMobileNativeIdentityConfig(repoRoot, {
      KANNA_APP_ENV: "dev"
    });

    expect(result.path).toBe(join(repoRoot, "apps/mobile/ios/KannaNativeIdentity.xcconfig"));
    expect(existsSync(join(repoRoot, "apps/mobile/ios"))).toBe(false);
  });

  it("patches only app-target build configurations to use native identity variables", () => {
    const input = `
/* Begin XCBuildConfiguration section */
		APP_DEBUG /* Debug */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				INFOPLIST_KEY_CFBundleDisplayName = Kanna;
				PRODUCT_BUNDLE_IDENTIFIER = build.kanna.app;
			};
			name = Debug;
		};
		TEST_DEBUG /* Debug */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				PRODUCT_BUNDLE_IDENTIFIER = build.kanna.app.KannaMobileTests;
			};
			name = Debug;
		};
/* End XCBuildConfiguration section */
/* Begin XCConfigurationList section */
		APP_LIST /* Build configuration list for PBXNativeTarget "KannaMobile" */ = {
			isa = XCConfigurationList;
			buildConfigurations = (
				APP_DEBUG /* Debug */,
			);
		};
		TEST_LIST /* Build configuration list for PBXNativeTarget "KannaMobileTests" */ = {
			isa = XCConfigurationList;
			buildConfigurations = (
				TEST_DEBUG /* Debug */,
			);
		};
/* End XCConfigurationList section */
`;

    const output = patchPbxprojNativeIdentity(input);

    expect(output).toContain("PRODUCT_BUNDLE_IDENTIFIER = $(KANNA_BUNDLE_ID);");
    expect(output).toContain("INFOPLIST_KEY_CFBundleDisplayName = $(KANNA_DISPLAY_NAME);");
    expect(output).toContain(
      "PRODUCT_BUNDLE_IDENTIFIER = build.kanna.app.KannaMobileTests;"
    );
  });

  it("builds and launches through the worktree Metro on the Mac LAN IP with native identity env", () => {
    const command = buildMobileDeviceRunCommand({
      repoRoot: "/repo",
      deviceUdid: "00008130-001015CA1091401C",
      lanHost: "172.16.0.193",
      metroPort: 1430,
      nativeIdentity: {
        appEnv: "dev",
        bundleId: "build.kanna.app.dev",
        displayName: "Kanna Dev"
      }
    });

    expect(command).toEqual({
      command: "pnpm",
      args: [
        "--dir",
        "/repo/apps/mobile",
        "ios",
        "--device",
        "00008130-001015CA1091401C",
        "--port",
        "1430"
      ],
      cwd: "/repo",
      env: {
        KANNA_APP_ENV: "dev",
        KANNA_BUNDLE_ID: "build.kanna.app.dev",
        KANNA_DISPLAY_NAME: "Kanna Dev",
        REACT_NATIVE_PACKAGER_HOSTNAME: "172.16.0.193",
        RCT_METRO_PORT: "1430"
      }
    });
  });

  it("checks LAN Metro reachability and installed app state with guidance", async () => {
    const calls: string[] = [];
    const runner: CommandRunner = {
      async run(command, args) {
        calls.push(`${command} ${args.join(" ")}`);
        if (command === "curl") {
          return { exitCode: 0, stdout: "packager-status:running\n", stderr: "" };
        }
        if (command === "xcrun") {
          return { exitCode: 0, stdout: "build.kanna.app.dev\n", stderr: "" };
        }
        return { exitCode: 0, stdout: "", stderr: "" };
      }
    };

    const result = await checkPhysicalDeviceRunPreflight(runner, {
      bundleId: "build.kanna.app.dev",
      device: device("Jerome's iPhone 15", "00008130-001015CA1091401C"),
      lanHost: "172.16.0.193",
      metroPort: 1430
    });

    expect(result.ok).toBe(true);
    expect(result.metroUrl).toBe("http://172.16.0.193:1430");
    expect(result.checks).toEqual([
      { name: "metro-lan", ok: true, message: "Metro is reachable at http://172.16.0.193:1430/status." },
      { name: "app-installed", ok: true, message: "build.kanna.app.dev is installed on Jerome's iPhone 15." },
      {
        name: "local-network-permission",
        ok: true,
        message: "On the iPhone, allow Local Network for Kanna in Settings -> Privacy & Security -> Local Network."
      }
    ]);
    expect(calls).toEqual([
      "curl --fail --silent --show-error http://172.16.0.193:1430/status",
      "xcrun devicectl device info apps --device 00008130-001015CA1091401C"
    ]);
  });
});
